// Para criar e armazenar os sprites do "Flappy Bird":

#include "sprites.h"

// Sprite do jogador 1, na posição 1:
// Paleta de Cores: Alpha, Black, White, Dark Silver, Golden Yellow, Orange e Scarlet.
const int bird_player1_position1[20][20] = {
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_DARK_SILVER, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_DARK_SILVER, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_DARK_SILVER, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_DARK_SILVER, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_DARK_SILVER, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_BLACK}, 
    {COLOR_BLACK, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_BLACK}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ORANGE, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}
};

// Sprite do jogador 1, na posição 2:
// Paleta de Cores: Alpha, Black, White, Dark Silver, Golden Yellow, Orange e Scarlet.
const int bird_player1_position2[20][20] = {
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_BLACK}, 
    {COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_BLACK}, 
    {COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_DARK_SILVER, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_DARK_SILVER, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_BLACK, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_BLACK, COLOR_ORANGE, COLOR_ORANGE, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}
};

// Sprite do jogador 2, na posição 1:
// Paleta de Cores: Alpha, Black, White, Dark Silver, Vivid Red, Burgundy e Golden Yellow.
const int bird_player2_position1[20][20] = {
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_DARK_SILVER, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_DARK_SILVER, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_DARK_SILVER, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_DARK_SILVER, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_DARK_SILVER, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK}, 
    {COLOR_BLACK, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BURGUNDY, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_VIVID_RED, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}
};

// Sprite do jogador 2, na posição 2:
// Paleta de Cores: Alpha, Black, White, Dark Silver, Vivid Red, Burgundy e Golden Yellow.
const int bird_player2_position2[20][20] = {
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK}, 
    {COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK}, 
    {COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_DARK_SILVER, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_DARK_SILVER, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_BLACK, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_BLACK, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}
};

// Desenhando um sprite na memória dos sprites, de acordo com o seu offset:
int sprite_builder(int offset, const int sprite_array[20][20]){
    offset = (offset+1) * 20; // Calculando as posições dos pixels de coluna de acordo com o offset.
    // Percorrendo o vetor bidimensional do sprite e o desenhando na memória dos sprites:
    for(int row = 0; row < 20; row++){
        for(int column = 0; column < 20; column++){
            if(sprite_array[row][column] > 0) // Verificando se há uma cor válida.
                sprite_drawing(row, column+(offset-20), sprite_array[row][column]);
        }
    }
    return 0;
}

// Armazenando os sprites na memória:
int flappy_bird_sprites(void){
    sprite_builder(26, bird_player1_position1); // Jogador 1, Posição 1, no Offset 26.
    sprite_builder(27, bird_player1_position2); // Jogador 1, Posição 2, no Offset 27.
    sprite_builder(28, bird_player2_position1); // Jogador 2, Posição 1, no Offset 28.
    sprite_builder(29, bird_player2_position2); // Jogador 2, Posição 2, no Offset 29.
    return 0;
}

// Animação dos sprites dos jogadores (03 FPS):
// Deverá ser usado em uma thread.
int sp_animation(void){
    while(!(player1_gameover && player2_gameover)){
        if(!player1_gameover){
            if(player1_sp_offset == 26)
                player1_sp_offset = 27;
            else
                player1_sp_offset = 26;   
        }
        if(!player2_gameover){
            if(player2_sp_offset == 28)
                player2_sp_offset = 29;
            else
                player2_sp_offset = 28;   
        }
        set_players();      // Atualizando o estado dos sprites dos jogadores.
        usleep(300 * 1000); // Aproximadamente, 03 FPS (Frames Per Second / Imagens por Segundo).
    }
    return 0;
}
