// Para criar e armazenar os sprites do "Flappy Bird":

#include "sprites.h"

// Sprite do jogador 1, na posição 1:
// Paleta de Cores: Alpha, Black, White, Dark Silver, Golden Yellow, Orange e Scarlet.
const int bird_player1_position1[20][20] = {
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_DARK_SILVER, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_DARK_SILVER, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_DARK_SILVER, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_DARK_SILVER, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_DARK_SILVER, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_BLACK}, 
    {COLOR_BLACK, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_BLACK}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ORANGE, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}
};

// Sprite do jogador 1, na posição 2:
// Paleta de Cores: Alpha, Black, White, Dark Silver, Golden Yellow, Orange e Scarlet.
const int bird_player1_position2[20][20] = {
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_BLACK}, 
    {COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_BLACK}, 
    {COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_DARK_SILVER, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_DARK_SILVER, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_BLACK, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_BLACK, COLOR_ORANGE, COLOR_ORANGE, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}
};

// Sprite do jogador 2, na posição 1:
// Paleta de Cores: Alpha, Black, White, Dark Silver, Vivid Red, Burgundy e Golden Yellow.
const int bird_player2_position1[20][20] = {
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_DARK_SILVER, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_DARK_SILVER, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_DARK_SILVER, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_DARK_SILVER, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_DARK_SILVER, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK}, 
    {COLOR_BLACK, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BURGUNDY, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_VIVID_RED, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}
};

// Sprite do jogador 2, na posição 2:
// Paleta de Cores: Alpha, Black, White, Dark Silver, Vivid Red, Burgundy e Golden Yellow.
const int bird_player2_position2[20][20] = {
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK}, 
    {COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK}, 
    {COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_DARK_SILVER, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_DARK_SILVER, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_BLACK, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_BLACK, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}
};

// Desenhando um sprite na memória dos sprites, de acordo com o seu offset:
int sprite_builder(int offset, const int sprite_array[20][20]){
    // Percorrendo o vetor bidimensional do sprite e o desenhando na memória dos sprites:
    for(int row = 0; row < 20; row++){
        for(int column = 0; column < 21; column++){
            buffer_overflow();
            sprite_drawing(row, column, bird_player1_position1[row][column]);
        }
    }
    for(int row = 20; row < 40; row++){
        for(int column = 0; column < 21; column++){
            buffer_overflow();
            sprite_drawing(row, column, bird_player1_position2[row-20][column]);
        }
    }
    for(int row = 40; row < 60; row++){
        for(int column = 0; column < 21; column++){
            buffer_overflow();
            sprite_drawing(row, column, bird_player2_position1[row-40][column]);
        }
    }
    for(int row = 60; row <= 80; row++){
        for(int column = 0; column < 21; column++){
            buffer_overflow();
            if(row < 80)
                sprite_drawing(row, column, bird_player2_position2[row-60][column]);
            else
                sprite_drawing(row, column, COLOR_ALPHA);
        }
    }
    return 0;
}

// Armazenando os sprites na memória:
int flappy_bird_sprites(void){
    sprite_builder(2, bird_player2_position1); // Jogador 2, Posição 1, no Offset 28.
    return 0;
}

// Animação dos sprites dos jogadores (03 FPS):
void* sp_animation(void* arg){
    while(!(player1_gameover && player2_gameover)){
        if(!player1_gameover){
            if(player1_sp_offset == 0)
                player1_sp_offset = 1;
            else
                player1_sp_offset = 0;   
        }
        if(!player2_gameover){
            if(player2_sp_offset == 2)
                player2_sp_offset = 3;
            else
                player2_sp_offset = 2;   
        }
        buffer_overflow();
        set_players();      // Atualizando o estado dos sprites dos jogadores.
        while(on_pause){}   // Estado de pausa do jogo.
        usleep(300 * 1000); // Aproximadamente, 03 FPS (Frames Per Second / Imagens por Segundo).
    }
    return NULL;
}
