// Para criar e armazenar os sprites do "Flappy Bird":

#include "sprites.h"

// Sprite do jogador 1, na posição 1:
// Paleta de Cores: Alpha, Black, White, Dark Silver, Golden Yellow, Orange e Scarlet.
const int bird_player1_position1[20][20] = {
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_DARK_SILVER, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_DARK_SILVER, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_DARK_SILVER, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_DARK_SILVER, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_DARK_SILVER, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_BLACK}, 
    {COLOR_BLACK, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_BLACK}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ORANGE, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}
};

// Sprite do jogador 1, na posição 2:
// Paleta de Cores: Alpha, Black, White, Dark Silver, Golden Yellow, Orange e Scarlet.
const int bird_player1_position2[20][20] = {
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_BLACK}, 
    {COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_BLACK}, 
    {COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_DARK_SILVER, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_DARK_SILVER, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_BLACK, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_BLACK, COLOR_ORANGE, COLOR_ORANGE, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_SCARLET, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}
};

// Sprite do jogador 2, na posição 1:
// Paleta de Cores: Alpha, Black, White, Dark Silver, Vivid Red, Burgundy e Golden Yellow.
const int bird_player2_position1[20][20] = {
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_DARK_SILVER, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_DARK_SILVER, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_DARK_SILVER, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_DARK_SILVER, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_DARK_SILVER, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK}, 
    {COLOR_BLACK, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BURGUNDY, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_VIVID_RED, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}
};

// Sprite do jogador 2, na posição 2:
// Paleta de Cores: Alpha, Black, White, Dark Silver, Vivid Red, Burgundy e Golden Yellow.
const int bird_player2_position2[20][20] = {
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK}, 
    {COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK}, 
    {COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_DARK_SILVER, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_DARK_SILVER, COLOR_BLACK, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_BLACK, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_DARK_SILVER, COLOR_BLACK, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_GOLDEN_YELLOW, COLOR_BLACK, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_BURGUNDY, COLOR_VIVID_RED, COLOR_VIVID_RED, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}, 
    {COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA, COLOR_ALPHA}
};

// Desenhando um sprite na memória dos sprites, de acordo com o seu offset:
int sprite_builder(int offset, const int sprite_array[20][20]){
    // Os sprites são desenhados verticalmente na memória:
    int row_start = 0 + (offset * 20); // Posição inicial do loop de linhas.
    int row_end = row_start + 20;      // Posição final do loop de linhas.
    // Percorrendo o array bidimensional e a memória dos sprites:
    for(int row = row_start; row < row_end; row++){
        for(int column = 0; column < 21; column++){
            buffer_overflow();
            sprite_drawing(row, column, sprite_array[row-row_start][column]);
        }
    }
    return 0;
}

// Armazenando os sprites do "Flappy Bird" na memória:
int flappy_bird_sprites(void){
    sprite_builder(0, bird_player1_position1); // Jogador 1, Posição 1, no Offset 0.
    sprite_builder(1, bird_player1_position2); // Jogador 1, Posição 2, no Offset 1.
    sprite_builder(2, bird_player2_position1); // Jogador 2, Posição 1, no Offset 2.
    sprite_builder(3, bird_player2_position2); // Jogador 2, Posição 2, no Offset 3.
    return 0;
}

// Animação dos sprites dos jogadores (03 FPS):
void* sp_animation(void* arg){
    while(!game_exit){
        if(!player1_gameover){
            if(player1_sp_offset == 0)
                player1_sp_offset = 1;
            else
                player1_sp_offset = 0;   
        }
        if(!player2_gameover){
            if(player2_sp_offset == 2)
                player2_sp_offset = 3;
            else
                player2_sp_offset = 2;   
        }
        buffer_overflow();
        set_players();      // Atualizando o estado dos sprites dos jogadores.
        while(on_pause){}   // Estado de pausa do jogo.
        usleep(300 * 1000); // Aproximadamente, 03 FPS (Frames Per Second / Imagens por Segundo).
    }
    return NULL;
}
